# Everything you need to know about python:
## In simplest possible way

# output formatting

    Output formatting refers to the process of customizing the appearance and structure of output generated by a program. It is particularly essential when displaying information to users in a readable and organized manner.

In [16]:
# considering some variables
name = 'Mahesh'
age = 21
location = 'India'

    I want to print the output of above variables like this meaningful information
    
    Name is Mahesh, age is 21 and location is India

## By placing variables wherever needed by sepeating text by ,(comma)

In [17]:
print('Name is',name,', age is ',age, ' and location is ',location)

Name is Mahesh , age is  21  and location is  India

## using % approach

In [18]:
print('Name is %s, age is %d and location is %s' %(name, age, location))

Name is Mahesh, age is 21 and location is India

## using str.format()

In [19]:
print("Name is {}, age is {} and location is {}".format(name,age, location))

Name is Mahesh, age is 21 and location is India

    If we mistakenly placed variables, by proper indexing we can get the meaningful output

In [20]:
print("Name is {1}, age is {0} and location is {2}".format(age,name, location)) 
# here age is given first then name but by mentioning indexed we can arrange them properly

Name is Mahesh, age is 21 and location is India

## f-string

In [21]:
print(f'Name is {name}, age is {age}, and location is {location}') # we can siply place variables wherever needed

Name is Mahesh, age is 21, and location is India

## formatting tip

    In str.format() in str by using {:.2f} this way we can customize the values after the decimal, here I want 2 numbers after decimal

In [25]:
value = 3.142352332
print('value is {:.2f}'.format(value))

value is 3.14

In [28]:
# if I have 
value1 = 3.14
print('value is {:.5f}'.format(value1)) # I want 5 values after the decimal --> so replaced with 0's

value is 3.14000

For more this kind of basic and andvanced python explore my channel https://www.youtube.com/@MaheshJaviniki and dont forget to subscribe